[Info]
name = "test 1"
version = "1"
source = "test.com/test1"
author = "test maker"

[Build]

deps = [
    { name = "test dep 1", version = "2" },
    { name = "test dep 2", version = "3" },
]

steps = ["echo test", "echo $1"]
